name: Build AirSense Flutter Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Add Flutter web support
        run: flutter create . --platforms web

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Upload Flutter Web Build
        uses: actions/upload-artifact@v4
        with:
          name: airsense-web
          path: frontend/build/web